### ISSUE TITLE
Fix for difficult to see target is wrong.

### ISSUE THREAD

**Issue by iandobbie** [MicronOxford/BeamDelta#11]
David's update making the cross bigger is the wrong fix I think. I think we need to make the lines thicker.  I think we should change line 245

        pen.setWidth(self.width()/500)

To something less than 500, maybe 200 or even 100?

**Comment by carandraug** [comment]
> David's update making the cross bigger is the wrong fix I think. [...]

I didn't make any such change. I guess you mean 3d658164485f5158fda which is signed by micron. Anyway, ian fixed the fix on the pull #21 so closing.
