### ISSUE TITLE
Stripy images

### ISSUE THREAD

**Issue by juliomateoslangerak** [MicronOxford/BeamDelta#15]
Hi,
I got the camera, same as yours and went to run BeamDelta but I'm running into some trouble. I get a very thin image (horizontal). When I stretch it it shows stripes (I attach some pictures). 
When I connect to the camera using the terminal everything looks fine and I get (through trigger_and_wait) a nice 2048x2048 numpy 16bit array.

Am I doing something wrong. The script serving the camera is 
``` python
import microscope.deviceserver as ds
from microscope.devices import device
from microscope.cameras.ximea import XimeaCamera
DEVICES = [device(XimeaCamera, '127.0.0.1', 8005,)]
ds.serve_devices(DEVICES)
```

and I launch BeamDelta like so:
```python
BeamDelta PYRO:XimeaCamera@127.0.0.1:8005
```
Everything seems to work fine with the demo camera

![IMG_3322](https://user-images.githubusercontent.com/7799110/70732518-d9d85a00-1d08-11ea-9345-d1a227c802d7.jpg)
![IMG_3323](https://user-images.githubusercontent.com/7799110/70732519-d9d85a00-1d08-11ea-906a-6300164cfa41.jpg)

**Comment by juliomateoslangerak** [comment]
So I looked a bit into this.
camera.get_sensor_shape returns a (0,0) tuple
``` python
from microscope.clients import DataClient
camera = DataClient('PYRO:XimeaCamera@127.0.0.1:8005')
camera.get_sensor_shape()
Out[4]: (0, 0)
camera.enable()
camera.get_sensor_shape()
Out[6]: (0, 0)
camera.get_all_settings()
Out[7]: 
{'transform': 0,
 'readout mode': 0,
 'binning': (1, 1),
 'roi': ROI(left=None, top=None, width=None, height=None)}
```

**Comment by juliomateoslangerak** [comment]
Hi, I'm closing this issue here cause I believe it belongs to microscope's Ximea module

**Comment by NickHallONBI** [comment]
@juliomateoslangerak I've encountered this issue before. The stripes appear because the (2048, 2048) image is being down-sampled to fit the window size. I see in the second image you tried to make the window bigger. If you make the UI even large than that, you should see the stripes disappear when the down-sampling gets less severe. If not, we may have a larger issue at hand...

**Comment by juliomateoslangerak** [comment]
There seems to be two issues. 
- the camera view is not properly sized. This is cause at initialization sensor shape is obtained from the image which returns (0,0) at the moment that no image was acquired. 
- The stripes seem to be an encoding issue. If I get the image as a uint8 things work fine.
