### ISSUE TITLE
Crosshairs invisible when camera is saturated

### ISSUE THREAD

**Issue by juliomateoslangerak** [MicronOxford/BeamDelta#18]
The crosshairs are invisible when the camera is saturated. They should draw on top of the image. 

Also, they are too thin and hard to see. A thicker (2-3 pixels) line would be nicer IMHO.

**Comment by iandobbie** [comment]
If you change the  QPainter.Composition mode to QPainter.CompositionMode_SourceIn this fixes the issue.

**Comment by iandobbie** [comment]
Fixed by changing coposition mode as said above
